### Create User Preference
POST http://localhost:5000/preferences/
Content-Type: application/json

{
  "description": "My favourite food is chocolate",
  "updatedBy": "User"
}

###

### Get All User Preferences
GET http://localhost:5000/preferences/
Accept: application/json

###

### Post Generate new index for preferences
POST http://localhost:5000/preferences/generate-index
Accept: application/json

###

### Update User Preference (replace :id with actual ID)
PUT http://localhost:5000/preferences/1
Content-Type: application/json

{
  "description": "My favourite food is watermelon",
  "updatedBy": "User"
}

###

### Delete User Preference (replace :id with actual ID)
DELETE http://localhost:5000/preferences/:id
Accept: application/json

###

### Create Chat Log
POST http://localhost:5000/chatlog/
Content-Type: application/json

{
  "sentBy": "Sender's Name or ID",
  "message": "The chat message text"
}

###

### Get All Chat Logs
GET http://localhost:5000/chatlog/
Accept: application/json

###

### Seed IoT Data 1
POST http://localhost:5000/iot_data/
Content-Type: application/json

{
  "topic": "esp32-dht22/TEMP_1",
  "unit": "°C",
  "location": "Kitchen",
  "data": {"value": 26},
  "time": "2024-04-01T14:00:00"
}

###

### Seed IoT Data 2
POST http://localhost:5000/iot_data/
Content-Type: application/json

{
  "topic": "esp32-dht22/HUMIDITY_1",
  "unit": "g/kg",
  "location": "Kitchen",
  "data": {"value": 10},
  "time": "2024-04-01T14:05:00"
}

###

### Seed IoT Data 3
POST http://localhost:5000/iot_data/
Content-Type: application/json

{
  "topic": "esp32-dht22/TEMP_2",
  "unit": "°C",
  "location": "Living Room",
  "data": {"value": 22},
  "time": "2024-04-01T14:10:00"
}

###
